## TOML Uranio
ssl_secure = false
dev_ssl_secure = false
[default_atoms]
	user = true
	media = true
	error = true
	request = true
[service]
	protocol = 'http'
	domain = 'uranio-bld.uranio.xyz'
	port = 4401
	proxy = 'https://uranio-bld.uranio.xyz:7701'
[dev.service]
	domain = '0.0.0.0'
	port = 1001
	proxy = 'http://localhost:1001'
[client.panel]
	protocol = 'http'
	domain = 'uranio-bld.uranio.xyz'
	port = 6601
	api_proxy = 'https://uranio-bld.uranio.xyz'
[client.dev.panel]
	domain = '0.0.0.0'
	port = 1002
	api_proxy = 'http://localhost:1002'
