## TOML Uranio
[default_atoms]
	user = false
	media = false
	request = true
	error = true
[service]
	protocol = 'https'
	domain = 'localhost'
	port = 7799
	url = 'https://localhost:7799/uranio/api'
[client.panel]
	protocol = 'https'
	domain = '0.0.0.0'
	port = 7788
[client.fetch]
	url = 'https://0.0.0.0:7788/uranio/api'
[log]
	debug_info = false
	color = true
