## TOML Uranio
ssl_secure = false
dev_ssl_secure = false
[default_atoms]
	user = true
	media = true
	error = true
	request = true
[service]
	protocol = 'http'
	domain = 'uranio-bld.uranio.xyz'
	port = 1107
[dev.service]
	domain = '0.0.0.0'
	port = 7373
[client.panel]
	protocol = 'http'
	domain = 'uranio-bld.uranio.xyz'
	port = 7101
[client.dev.panel]
	domain = '0.0.0.0'
	port = 8383
[client.api]
	proxy = 'https://uranio-bld.uranio.xyz:7701/uranio/api'
[client.dev.api]
	proxy = ''
