## TOML Uranio
[service]
	protocol = 'https'
	domain = '0.0.0.0'
	port = 7799
	url = 'https://0.0.0.0:443/uranio/api'
[client.panel]
	protocol = 'https'
	domain = '0.0.0.0'
	port = 443
[client.service]
	url = 'https://0.0.0.0:443/uranio/api'
