## TOML Uranio
[service]
	protocol = 'https'
	domain = '0.0.0.0'
	port = 7171
[dev.service]
	port = 7373
[client.panel]
	protocol = 'https'
	domain = '0.0.0.0'
	port = 8181
[client.dev.panel]
	port = 8383
