## TOML Uranio
ssl_secure = false
dev_ssl_secure = false
[default_atoms]
	user = true
	media = true
	error = true
	request = true
[service]
	protocol = 'https'
	domain = 'uranio-bld.x81da.com'
	port = 7777
[dev.service]
	domain = '0.0.0.0'
	port = 7373
[client.panel]
	protocol = 'https'
	domain = 'uranio-bld.x81da.com'
	port = 443
[client.dev.panel]
	domain = '0.0.0.0'
	port = 8383
