## TOML Uranio
ssl_secure = false
dev_ssl_secure = false
[service]
	protocol = 'https'
	domain = 'ec2-15-161-110-3.eu-south-1.compute.amazonaws.com'
	port = 7777
[dev.service]
	domain = '0.0.0.0'
	port = 7373
[client.panel]
	protocol = 'https'
	domain = '0.0.0.0'
	port = 443
[client.dev.panel]
	port = 8383
