# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Uranio Docker Image

on:
  push:
    branches:
      - master

env:
  REGISTRY: registry.gitlab.com
  REGISTRY_USERNAME: x71c9
  FULL_TAG: registry.gitlab.com/uranio/${{ github.event.repository.name }}
  # IMAGE_NAME: ${{ github.repository }}

jobs:
  push_to_registry:
    name: Push Uranio Docker image to Docker Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Log in to Docker Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD_TOKEN }}

      - name: Configure SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Uranio
        run: yarn global add uranio

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Init Uranio
        run: uranio init -uf --prod --docker --repo=adm

      - name: Uranio Push to Docker Registry
        run: uranio docker push --docker_tag="${{ env.FULL_TAG }}:${{ steps.vars.outputs.sha_short }}"


